version: '3'
services: 
    front:
        container_name: copang-front
        build: 
            context: .
            dockerfile: Dockerfile
        expose: 
            - "3000"

networks: 
    default:
        external: true
        name: main_default